### ISSUE TITLE
angle in grain analysis is `None`

### ISSUE THREAD

**Issue by tschaume** [materialsproject/crystaltoolkit#236]
```
builtins.TypeError: `id` prop must be a string or dict, not None
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/crystal_toolkit/components/transformations/core.py", line 371, in apply_transformation
    struct = transformation.apply_transformation(struct)
  File "/root/.local/lib/python3.9/site-packages/pymatgen/transformations/advanced_transformations.py", line 1466, in apply_transformation
    gb_struct = gbg.gb_from_parameters(
  File "/root/.local/lib/python3.9/site-packages/pymatgen/analysis/gb/grain.py", line 591, in gb_from_parameters
    t1, t2 = self.get_trans_mat(
  File "/root/.local/lib/python3.9/site-packages/pymatgen/analysis/gb/grain.py", line 1206, in get_trans_mat
    if abs(angle - 180.0) < 1.0e0:
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/ddtrace/contrib/flask/helpers.py", line 36, in wrapper
    return wrapped(*args, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/lib/python3.9/site-packages/ddtrace/contrib/flask/helpers.py", line 25, in wrapper
    return func(pin, wrapped, instance, args, kwargs)
  File "/root/.local/lib/python3.9/site-packages/ddtrace/contrib/flask/patch.py", line 480, in _traced_request
    return wrapped(*args, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/root/.local/lib/python3.9/site-packages/ddtrace/contrib/flask/wrappers.py", line 25, in trace_func
    return wrapped(*args, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/dash/dash.py", line 1383, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/root/.local/lib/python3.9/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/root/.local/lib/python3.9/site-packages/crystal_toolkit/components/transformations/core.py", line 447, in run_transformations
    struct, error = apply_transformation(transformation_data, struct)
  File "/root/.local/lib/python3.9/site-packages/flask_caching/__init__.py", line 952, in decorated_function
    rv = f(*args, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/crystal_toolkit/components/transformations/core.py", line 377, in apply_transformation
    traceback_info = Reveal(
  File "/root/.local/lib/python3.9/site-packages/crystal_toolkit/helpers/layouts.py", line 269, in __init__
    html.Div(
  File "/root/.local/lib/python3.9/site-packages/dash/development/base_component.py", line 425, in wrapper
    return func(*args, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/dash/html/Div.py", line 181, in __init__
    super(Div, self).__init__(children=children, **args)
  File "/root/.local/lib/python3.9/site-packages/dash/development/base_component.py", line 164, in __init__
    raise TypeError(
TypeError: `id` prop must be a string or dict, not None
```

**Comment by mkhorton** [comment]
Closed with dbbd238c7785e1fa452edf232081aac27fc74e78
