### ISSUE TITLE
[Bug]: Install error Cannot unpack file /tmp/pip-unpack-_d5u6dgt/crystaltoolkit

### ISSUE THREAD

**Issue by cedricrocha** [materialsproject/crystaltoolkit#399]
### Code snippet

```python
pip install https://github.com/materialsproject/crystaltoolkit
Defaulting to user installation because normal site-packages is not writeable
Collecting https://github.com/materialsproject/crystaltoolkit
  Downloading https://github.com/materialsproject/crystaltoolkit
     / 406.0 kB 27.5 kB/s 0:00:13
  ERROR: Cannot unpack file /tmp/pip-unpack-_d5u6dgt/crystaltoolkit (downloaded from /tmp/pip-req-build-nqy_xmc1, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-nqy_xmc1
```

### What happened?

Hello
 
I'm trying to install crystaltoolkit from pip install and getting errors like 

ERROR: Exception:
Traceback (most recent call last):
  File "/home/cedric/.local/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3070, in _dep_map
    return self.__dep_map
  File "/home/cedric/.local/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2863, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

So I tried instead installing from github. 

pip install https://github.com/materialsproject/crystaltoolkit
Defaulting to user installation because normal site-packages is not writeable
Collecting https://github.com/materialsproject/crystaltoolkit
  Downloading https://github.com/materialsproject/crystaltoolkit
     / 406.0 kB 27.5 kB/s 0:00:13
  ERROR: Cannot unpack file /tmp/pip-unpack-_d5u6dgt/crystaltoolkit (downloaded from /tmp/pip-req-build-nqy_xmc1, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-nqy_xmc1
 
Can you please help me? 

### Version

Ubuntu 20.04.6 LTS

### Which OS?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### Log output

```shell
ERROR: Cannot unpack file /tmp/pip-unpack-_d5u6dgt/crystaltoolkit (downloaded from /tmp/pip-req-build-nqy_xmc1, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-nqy_xmc1
```

**Comment by cedricrocha** [comment]
Cannot install crystal-toolkit.

**Comment by mkhorton** [comment]
Hi Cedric, happy to try and help you. I suspect this might be more likely related to your system setup than a bug.

Can you tell me what version of Python you're using, if you're using conda or other package managers, and if you've managed to install other scientific Python software ok?

**Comment by cedricrocha** [comment]
> Hi Cedric, happy to try and help you. I suspect this might be more likely related to your system setup than a bug.
> 
> Can you tell me what version of Python you're using, if you're using conda or other package managers, and if you've managed to install other scientific Python software ok?

Hello @mkhorton. Thanks for your answer! I am running python3.8 and I use pip 24.2. Here's might be the catch: I had just installed pymatgen when I got a message asking me to update pip. So I did and after that I could not install crystal-toolkit. So I tried downgrading to pip 24.1. Same error. I tried a beta version of pip. Still no success. Pymatgen did install and is operating. I am running Ubuntu  Ubuntu 20.04.6 LTS. Thanks!
