### ISSUE TITLE
Cannot start dev server

### ISSUE THREAD

**Issue by dwinston** [materialsproject/crystaltoolkit#65]
I checked out the repo, did
```
conda create -n xtaltoolkit python=3.7
pip install numpy scipy
pip install -r requirements.txt
pip install pythreejs
python app.py
```
and got the following:
```
(xtaltoolkit) Donnys-MBP:crystaltoolkit dwinston$ python app.py
/Users/dwinston/repos/crystaltoolkit/crystal_toolkit/components/core.py:39: UserWarning:

Caching has not been set up, app performance may be degraded.

Traceback (most recent call last):
  File "app.py", line 171, in <module>
    html.Div([transformation_component.standard_layout]),
  File "/Users/dwinston/repos/crystaltoolkit/crystal_toolkit/components/transformations/core.py", line 216, in standard_layout
    self.choices_layout,
  File "/Users/dwinston/repos/crystaltoolkit/crystal_toolkit/components/core.py", line 221, in __getattr__
    and item.split("_layout")[0] in self.supported_layouts
  File "/Users/dwinston/repos/crystaltoolkit/crystal_toolkit/components/core.py", line 233, in supported_layouts
    return self.all_layouts.keys()
  File "/Users/dwinston/repos/crystaltoolkit/crystal_toolkit/components/transformations/core.py", line 176, in all_layouts
    for name, transformation in self.transformations.items()
  File "/Users/dwinston/repos/crystaltoolkit/crystal_toolkit/components/transformations/core.py", line 176, in <listcomp>
    for name, transformation in self.transformations.items()
  File "/Users/dwinston/repos/crystaltoolkit/crystal_toolkit/components/core.py", line 221, in __getattr__
    and item.split("_layout")[0] in self.supported_layouts
  File "/Users/dwinston/repos/crystaltoolkit/crystal_toolkit/components/core.py", line 233, in supported_layouts
    return self.all_layouts.keys()
  File "/Users/dwinston/repos/crystaltoolkit/crystal_toolkit/components/transformations/core.py", line 44, in all_layouts
    options = html.Div(self.options_layout, id=self.id("options"))
  File "/Users/dwinston/repos/crystaltoolkit/crystal_toolkit/components/transformations/supercell.py", line 37, in options_layout
    options = get_matrix_input(self.id(), label="Scaling matrix")
  File "/Users/dwinston/repos/crystaltoolkit/crystal_toolkit/helpers/inputs.py", line 93, in get_matrix_input
    row.append(matrix_element(f"{i}{j}", value=default[i][j]))
  File "/Users/dwinston/repos/crystaltoolkit/crystal_toolkit/helpers/inputs.py", line 85, in matrix_element
    value=value,
  File "/Users/dwinston/miniconda3/envs/xtaltoolkit/lib/python3.7/site-packages/dash/development/base_component.py", line 323, in wrapper
    return func(*args, **kwargs)
  File "/Users/dwinston/miniconda3/envs/xtaltoolkit/lib/python3.7/site-packages/dash_core_components/Input.py", line 89, in __init__
    super(Input, self).__init__(**args)
  File "/Users/dwinston/miniconda3/envs/xtaltoolkit/lib/python3.7/site-packages/dash/development/base_component.py", line 94, in __init__
    ', '.join(sorted(self._prop_names))
TypeError: Unexpected keyword argument `inputmode`
Allowed arguments: autoComplete, autoFocus, className, debounce, disabled, id, inputMode, list, loading_state, max, maxLength, min, minLength, multiple, n_blur, n_blur_timestamp, n_submit, n_submit_timestamp, name, pattern, placeholder, readOnly, required, selectionDirection, selectionEnd, selectionStart, size, spellCheck, step, style, type, value
(xtaltoolkit) Donnys-MBP:crystaltoolkit dwinston$
```

Please advise.

**Comment by mkhorton** [comment]
This is due to a breaking change in the latest Dash, `inputmode` became `inputMode`. I have a local fix but haven't pushed yet, but a find-and-replace should be sufficient.

**Comment by mkhorton** [comment]
Should be fixed with https://github.com/materialsproject/crystaltoolkit/commit/76be7f13322e20ac8d7e5d9bf71a5a5b16968e5c please re-open if it's not :)

**Comment by dwinston** [comment]
Thanks!
